// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsVZfI-78ChwMHRGF-f9GGhrgh3gyTiZc',
    appId: '1:726532824965:web:cb61e917734c00a33b6eec',
    messagingSenderId: '726532824965',
    projectId: 'visit-manager-system',
    authDomain: 'visit-manager-system.firebaseapp.com',
    storageBucket: 'visit-manager-system.firebasestorage.app',
    measurementId: 'G-XZEN0Q8245',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKhb-4anlAYC5BzVbEj0lM-fhC-JeVvAA',
    appId: '1:726532824965:android:852425b5a59b8e763b6eec',
    messagingSenderId: '726532824965',
    projectId: 'visit-manager-system',
    storageBucket: 'visit-manager-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuNDw7kevcBQKIr3jpzo2nVvAxpJbnOR8',
    appId: '1:726532824965:ios:bb47504364e866ae3b6eec',
    messagingSenderId: '726532824965',
    projectId: 'visit-manager-system',
    storageBucket: 'visit-manager-system.firebasestorage.app',
    iosBundleId: 'com.example.fieldVisitManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuNDw7kevcBQKIr3jpzo2nVvAxpJbnOR8',
    appId: '1:726532824965:ios:bb47504364e866ae3b6eec',
    messagingSenderId: '726532824965',
    projectId: 'visit-manager-system',
    storageBucket: 'visit-manager-system.firebasestorage.app',
    iosBundleId: 'com.example.fieldVisitManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsVZfI-78ChwMHRGF-f9GGhrgh3gyTiZc',
    appId: '1:726532824965:web:799a74ededf063e53b6eec',
    messagingSenderId: '726532824965',
    projectId: 'visit-manager-system',
    authDomain: 'visit-manager-system.firebaseapp.com',
    storageBucket: 'visit-manager-system.firebasestorage.app',
    measurementId: 'G-JM7BEBKDJ3',
  );
}
